{
  "comments": [
    {
      "key": {
        "uuid": "a33697e3_840f14a0",
        "filename": "/COMMIT_MSG",
        "patchSetId": 2
      },
      "lineNbr": 10,
      "author": {
        "id": 1000414
      },
      "writtenOn": "2021-08-23T08:47:27Z",
      "side": 1,
      "message": "Can you explain why is this considered error?",
      "range": {
        "startLine": 10,
        "startChar": 23,
        "endLine": 10,
        "endChar": 28
      },
      "revId": "d2d4d92d3c7fdd5c2a74220aa14ae9e2c0b95a70",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "a1ce2384_0e0d205e",
        "filename": "/COMMIT_MSG",
        "patchSetId": 2
      },
      "lineNbr": 11,
      "author": {
        "id": 1000414
      },
      "writtenOn": "2021-08-23T08:47:27Z",
      "side": 1,
      "message": "Please include \u0027Tested\u0027 field.",
      "revId": "d2d4d92d3c7fdd5c2a74220aa14ae9e2c0b95a70",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    }
  ]
}