{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "9d3b9e1d_060527b6",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 17
      },
      "lineNbr": 0,
      "author": {
        "id": 1000056
      },
      "writtenOn": "2025-07-29T07:12:11Z",
      "side": 1,
      "message": "LGTM, but CI failure needs to be resolved.",
      "revId": "d34f5f1697ab9d8b2f5a8ce361a7dce671429d24",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}